### ISSUE TITLE
Fix bug with react-router and nginx 404 error

### ISSUE THREAD

**Issue by seductorAmadeus** [sdLiticaProject/code-ui#4]
Links: 
1. https://coderrocketfuel.com/article/fix-404-error-when-using-react-rouder-dom-and-nginx
2. https://stackoverflow.com/questions/45598779/react-router-browserrouter-leads-to-404-not-found-nginx-error-when-going-to

**Comment by ivan-perl** [comment]
At least this branch is opening well: http://sdlitica.sdcloud.io/ui/dev
