### ISSUE TITLE
Fix problem with 502 error on  api requests (e.g. when you're trying to send login request problem exists) and with inaccessible documentation page

### ISSUE THREAD

**Issue by seductorAmadeus** [sdLiticaProject/code-ui#5]
![image](https://user-images.githubusercontent.com/18173541/107324744-9ff41680-6ab9-11eb-96af-65290ee56b29.png)
![image](https://user-images.githubusercontent.com/18173541/107324791-b39f7d00-6ab9-11eb-85b3-ffd512d63bcb.png)

**Comment by ivan-perl** [comment]
Server was recovered
